weather:
  api_key: "YOUR_OPENWEATHERMAP_API_KEY"
  city_name: "London"
  units: "metric"
  language: "en"
  update_interval_minutes: 30
  forecast_days: 5
  hourly_forecast_count: 24

display:
  width: 1872
  height: 1404
  rotate: 0
  refresh_interval_minutes: 30
  partial_refresh: true
  # Image difference configuration
  pixel_diff_threshold: 10  # Threshold for considering a pixel changed
  pixel_diff_threshold_low_battery: 20  # Threshold when battery is low
  pixel_diff_threshold_critical_battery: 30  # Threshold when battery is critical
  min_changed_pixels: 100  # Minimum number of changed pixels to trigger refresh
  min_changed_pixels_low_battery: 250  # Minimum when battery is low
  min_changed_pixels_critical_battery: 500  # Minimum when battery is critical
  battery_aware_threshold: true  # Whether to adjust thresholds based on battery
  # Display formatting
  timestamp_format: "%Y-%m-%d %H:%M"
  time_format: null
  pressure_units: "hPa"  # Options: "hPa", "mmHg", "inHg"
  display_datetime_format: null  # Options: null (default to MM/DD/YYYY HH:MM AM/PM) or custom strftime format like "%m/%d/%Y %I:%M %p"

power:
  quiet_hours_start: "23:00"
  quiet_hours_end: "06:00"
  low_battery_threshold: 20
  critical_battery_threshold: 10
  wake_up_interval_minutes: 60
  wifi_timeout_seconds: 30
  disable_hdmi: true
  disable_bluetooth: true
  disable_leds: true
  enable_temp_fs: true
  cpu_governor: "powersave"
  cpu_max_freq_mhz: 700

server:
  url: "http://your-unraid-server-ip"
  port: 8000
  timeout_seconds: 10
  retry_attempts: 3
  retry_delay_seconds: 5
  cache_dir: "/tmp/weather-cache"
  log_level: "INFO"
  image_format: "PNG"

logging:
  level: "INFO"
  format: "json"
  max_size_mb: 5
  backup_count: 3

debug: false
development_mode: true
