weather:
  api_key: "YOUR_OPENWEATHERMAP_API_KEY"
  location: {"lat": 51.5072, "lon": -0.1276}  # Precise lat/lon coordinates for London
  city_name: "London"  # Used for display and when lat/lon not provided
  units: "metric"
  language: "en"
  update_interval_minutes: 30
  forecast_days: 5
  hourly_forecast_count: 24

display:
  width: 1872
  height: 1404
  rotate: 0
  vcom: -2.06  # VCOM value specific to e-paper display hardware
  # Refresh rate configuration
  refresh_interval_minutes: 30
  refresh_interval_low_battery_minutes: 60  # Interval when battery is low
  refresh_interval_critical_battery_minutes: 120  # Interval when battery is critical
  refresh_interval_charging_minutes: 15  # Interval when charging
  battery_aware_refresh: true  # Whether to adjust refresh intervals based on battery
  partial_refresh: true
  # Image difference configuration
  pixel_diff_threshold: 10  # Threshold for considering a pixel changed
  pixel_diff_threshold_low_battery: 20  # Threshold when battery is low
  pixel_diff_threshold_critical_battery: 30  # Threshold when battery is critical
  min_changed_pixels: 100  # Minimum number of changed pixels to trigger refresh
  min_changed_pixels_low_battery: 250  # Minimum when battery is low
  min_changed_pixels_critical_battery: 500  # Minimum when battery is critical
  battery_aware_threshold: true  # Whether to adjust thresholds based on battery
  # Display formatting
  timestamp_format: "%Y-%m-%d %H:%M"
  time_format: null
  pressure_units: "hPa"  # Options: "hPa", "mmHg", "inHg"
  display_datetime_format: null  # Options: null (default to MM/DD/YYYY HH:MM AM/PM) or custom strftime format like "%m/%d/%Y %I:%M %p"

power:
  quiet_hours_start: "23:00"
  quiet_hours_end: "06:00"
  low_battery_threshold: 20
  critical_battery_threshold: 10
  battery_capacity_mah: 12000  # Battery capacity in milliamp-hours
  wake_up_interval_minutes: 60
  wifi_timeout_seconds: 30
  enable_battery_aware_wifi: true
  wifi_power_save_mode: "auto"  # Options: "auto", "off", "on", "aggressive"
  retry_initial_delay_seconds: 1.0
  retry_max_delay_seconds: 300.0  # 5 minutes max delay
  retry_backoff_factor: 2.0
  retry_jitter_factor: 0.1  # 10% jitter
  retry_max_attempts: 5
  disable_hdmi: true
  disable_bluetooth: true
  disable_leds: true
  enable_temp_fs: true
  cpu_governor: "powersave"
  cpu_max_freq_mhz: 700
  enable_pijuice_events: true
  low_charge_action: "SYSTEM_HALT"  # Options: "NO_ACTION", "SYSTEM_HALT", "SYSTEM_HALT_POW_OFF", "SYSTEM_POWER_OFF", "SYSTEM_POWER_ON", "SYSTEM_REBOOT", "SYSTEM_WAKEUP"
  low_charge_delay: 5  # Delay in seconds before taking action
  button_press_action: "SYSDOWN"  # Action for button press (SW1)
  button_press_delay: 180  # Delay in seconds for button press (SW1)

server:
  url: "http://your-unraid-server-ip"
  port: 8000
  timeout_seconds: 10
  retry_attempts: 3
  retry_delay_seconds: 5
  cache_dir: "/tmp/weather-cache-1000"  # Uses gettempdir() and user ID by default
  log_level: "INFO"
  image_format: "PNG"

logging:
  level: "INFO"
  file: null  # Optional log file path, null uses stdout/stderr
  format: "json"
  max_size_mb: 5
  backup_count: 3

debug: false
development_mode: true
