weather:
  api_key: "your_openweathermap_api_key_here"
  city_name: "Atlanta"
  units: "metric"
  language: "en"
  update_interval_minutes: 30
  forecast_days: 5

display:
  width: 1872
  height: 1404
  rotate: 0
  refresh_interval_minutes: 30
  partial_refresh: true
  timestamp_format: "%Y-%m-%d %H:%M"

power:
  quiet_hours_start: "23:00"
  quiet_hours_end: "06:00"
  low_battery_threshold: 20
  critical_battery_threshold: 10
  wake_up_interval_minutes: 60
  wifi_timeout_seconds: 30
  disable_hdmi: true
  disable_bluetooth: true
  disable_leds: true
  enable_temp_fs: true
  cpu_governor: "powersave"
  cpu_max_freq_mhz: 700

server:
  url: "http://your-unraid-server-ip"
  port: 8000
  timeout_seconds: 10
  retry_attempts: 3
  retry_delay_seconds: 5
  cache_dir: "/tmp/weather-cache"
  log_level: "INFO"
  image_format: "PNG"

logging:
  level: "INFO"
  format: "json"
  max_size_mb: 5
  backup_count: 3

debug: false
development_mode: true
