name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Add permissions needed for GitHub Container Registry and CodeQL
permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Improved caching for Poetry
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction --all-extras

      - name: Lint with ruff
        run: |
          poetry run ruff check .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Improved caching for Poetry
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction --all-extras

      - name: Type check with pyright
        run: |
          # Create a pyrightconfig.json file to handle CI-specific settings
          echo '{
            "venvPath": "./.venv",
            "venv": ".",
            "reportUnknownVariableType": false,
            "reportUnknownMemberType": false,
            "reportUnknownArgumentType": false,
            "reportGeneralTypeIssues": false,
            "reportMissingImports": false
          }' > pyrightconfig.json
          poetry run pyright .

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      # Improved caching for Poetry
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: |
          poetry install --no-interaction --all-extras
          pip install safety
      
      - name: Run safety check
        run: |
          # Create requirements.txt from installed packages
          pip freeze > requirements.txt
          safety check -r requirements.txt
  
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install code metrics tools
        run: pip install radon
        
      - name: Check code complexity
        id: complexity
        run: |
          echo "::group::Code Complexity Analysis"
          # Generate a detailed report
          radon cc src/ -a -nc
          
          # Count the number of complex functions (rank D or worse)
          COMPLEX_COUNT=$(radon cc src/ -a -nc --json | grep -E '"rank": "[EF]"' | wc -l)
          
          echo "Complex functions (rank E-F): $COMPLEX_COUNT"
          echo "::endgroup::"
          
          # Only fail if we have excessively complex functions
          if [ "$COMPLEX_COUNT" -gt 5 ]; then
            echo "::error::Too many complex functions ($COMPLEX_COUNT > 5)"
            exit 1
          fi
          
      - name: Check maintainability index
        run: |
          echo "::group::Maintainability Index"
          radon mi src/ -s
          echo "::endgroup::"
  
  codeql:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v3
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
          upload: true

  test:
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    strategy:
      matrix:
        test-group: [models, client, server, utils]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Improved caching for Poetry
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
            
      # Playwright browsers cache
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction --all-extras

      - name: Run tests for ${{ matrix.test-group }}
        run: |
          # Create a temporary .coveragerc to override the fail_under setting
          echo "[report]
          fail_under = 0" > .coveragerc
          
          # Run tests with the local .coveragerc to override the settings in pyproject.toml
          poetry run pytest tests/${{ matrix.test-group }}/ --cov=src/ --cov-branch --cov-report=xml -v

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          flags: ${{ matrix.test-group }}

  upload-combined-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      # Improved caching for Poetry
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
            
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true
            
      - name: Install dependencies
        run: |
          poetry install --no-interaction --all-extras
            
      - name: Run all tests with coverage and JUnit report
        run: |
          # Remove any .coveragerc file that might have been created
          rm -f .coveragerc
          
          # Run with the settings from pyproject.toml (94% minimum)
          poetry run pytest --cov=src/ --cov-branch --cov-report=xml --junitxml=junit.xml -o junit_family=legacy
            
      - name: Upload JUnit test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: [lint, typecheck, test, security-scan, code-quality, codeql, upload-combined-coverage]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/rpi-weather-display
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=semver,pattern={{version}}
            latest

      # Cache Docker layers - use paths that exist with buildx
      - name: Setup Docker buildx cache
        uses: actions/cache@v3
        with:
          path: /home/runner/.docker/buildx
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Use GitHub cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Enable BuildKit
          builder: ${{ steps.buildx.outputs.name }}
          # Additional optimizations
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to server
        # This is a placeholder. In a real environment, you would have
        # steps to deploy to your Unraid server via SSH, Docker Compose,
        # or other deployment methods.
        run: |
          echo "Deploying to server - this is a placeholder"
          echo "In a real deployment, you would add steps to:"
          echo "- SSH into your Unraid server"
          echo "- Pull the latest Docker image"
          echo "- Restart the container"